name: tolab
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.3
  provider: ^6.1.5
  supabase_flutter: ^2.9.1
  font_awesome_flutter: ^10.8.0
  share_plus: ^11.0.0
  file_picker: ^10.2.0
  fluttertoast: ^8.2.12
  app_links: ^6.4.0
  firebase_core: ^3.1.0
  firebase_auth: ^6.0.0
  cloud_firestore: ^6.0.0
  mailer: ^6.4.1
  pin_code_fields: ^8.0.1
  google_sign_in: ^7.1.1
  google_sign_in_platform_interface: ^3.0.0
  image_picker: ^1.1.2
  intl: ^0.20.2
  http: ^1.4.0
  firebase_messaging: ^16.0.0  
  flutter_bloc: ^9.1.1
  bloc: ^9.0.0
  meta: ^1.16.0
  flutter_local_notifications: ^19.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  build_runner: ^2.4.6
  flutter_native_splash: ^2.4.0
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/image_splash/Tolab_splash_page.png
    - assets/image_App/Tolab.png
    - assets/image_App/google_logo.png

flutter_native_splash:
  color: "#FFFFFFFF"
  image: assets/image_App/Tolab.png
  android: true
  ios: true
  fullscreen: true
  android_gravity: center
  ios_content_mode: scaleAspectFill
