name: tolab_fci
description: "Premium university LMS mobile app."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.7.2
  dio: ^5.9.0
  pretty_dio_logger: ^1.4.0
  flutter_secure_storage: ^9.2.4
  shared_preferences: ^2.5.3
  connectivity_plus: ^6.1.5
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  flutter_staggered_animations: ^1.1.1
  google_fonts: ^6.3.1
  intl: ^0.20.2
  lottie: ^3.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/lottie/
    - assets/lang/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/iconapp.png"

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/splash_n.jpeg

  android: true
  ios: true

  android_12:
    color: "#FFFFFF"
    image: assets/images/splash_n.jpeg
    icon_background_color: "#FFFFFF"
