import 'package:flutter/material.dart';

import '../../shared/models/academic_models.dart';
import '../../shared/models/auth_models.dart';
import '../../shared/models/content_models.dart';
import '../../shared/models/dashboard_models.dart';
import '../../shared/models/moderation_models.dart';
import '../../shared/models/notification_models.dart';
import '../../shared/models/schedule_models.dart';
import '../../shared/models/settings_models.dart';
import '../../shared/models/staff_member.dart';
import '../../shared/models/student.dart';
import '../../modules/staff/models/staff_admin_models.dart';
import '../colors/app_colors.dart';

class DemoDataService {
  const DemoDataService();

  UserProfile adminProfile() => const UserProfile(
    id: '1',
    name: 'Dr. Laila Hassan',
    email: 'admin@tolab.edu',
    role: 'super_admin',
    status: 'active',
    department: 'Engineering',
  );

  DashboardBundle dashboardBundle() => DashboardBundle(
    metrics: const [
      KpiMetric(
        label: 'Active students',
        value: '12,480',
        delta: '+8.4% vs last month',
        color: AppColors.primary,
        icon: Icons.school_rounded,
      ),
      KpiMetric(
        label: 'Academic staff',
        value: '684',
        delta: '+21 new assignments',
        color: AppColors.secondary,
        icon: Icons.groups_rounded,
      ),
      KpiMetric(
        label: 'Schedule events',
        value: '1,246',
        delta: '92 awaiting review',
        color: AppColors.purple,
        icon: Icons.calendar_month_rounded,
      ),
      KpiMetric(
        label: 'Moderation alerts',
        value: '18',
        delta: '-11 resolved today',
        color: AppColors.warning,
        icon: Icons.shield_moon_rounded,
      ),
    ],
    trends: const [
      TrendPoint('Jan', 420),
      TrendPoint('Feb', 510),
      TrendPoint('Mar', 560),
      TrendPoint('Apr', 610),
      TrendPoint('May', 700),
      TrendPoint('Jun', 820),
    ],
    distribution: const [
      DistributionSlice(label: 'Lectures', value: 42, color: AppColors.primary),
      DistributionSlice(
        label: 'Sections',
        value: 28,
        color: AppColors.secondary,
      ),
      DistributionSlice(label: 'Exams', value: 18, color: AppColors.warning),
      DistributionSlice(label: 'Tasks', value: 12, color: AppColors.purple),
    ],
    activities: const [
      ActivityItem(
        title: 'New staff assignment approved',
        subtitle: 'Computer Science / Data Structures',
        timestamp: '12 min ago',
        type: 'staff',
      ),
      ActivityItem(
        title: 'Bulk enrollment imported',
        subtitle: '312 students added to Spring 2026 offerings',
        timestamp: '48 min ago',
        type: 'enrollment',
      ),
      ActivityItem(
        title: 'Reported message removed',
        subtitle: 'Group: CS-4B collaborative channel',
        timestamp: '1h ago',
        type: 'moderation',
      ),
    ],
    alerts: const [
      '2 course offerings exceeded room capacity',
      '6 notification campaigns are queued for the evening',
      '4 uploaded files need manual virus review',
    ],
  );

  List<Student> students() => const [
    Student(
      id: 'ST-1001',
      name: 'Omar Adel',
      email: 'omar.adel@tolab.edu',
      department: 'Computer Science',
      level: 'Level 4',
      section: 'CS-4A',
      status: 'active',
      gpa: 3.72,
      enrolledSubjects: 6,
    ),
    Student(
      id: 'ST-1002',
      name: 'Mariam Tarek',
      email: 'mariam.tarek@tolab.edu',
      department: 'Information Systems',
      level: 'Level 3',
      section: 'IS-3B',
      status: 'active',
      gpa: 3.88,
      enrolledSubjects: 5,
    ),
    Student(
      id: 'ST-1003',
      name: 'Youssef Ali',
      email: 'youssef.ali@tolab.edu',
      department: 'Engineering',
      level: 'Level 2',
      section: 'ENG-2A',
      status: 'inactive',
      gpa: 2.94,
      enrolledSubjects: 4,
    ),
  ];

  List<StaffMember> staff() => const [
    StaffMember(
      id: 'SF-201',
      name: 'Dr. Hadeer Salah',
      email: 'hadeer.salah@tolab.edu',
      title: 'Doctor',
      department: 'Computer Science',
      subjects: 3,
      status: 'active',
    ),
    StaffMember(
      id: 'SF-202',
      name: 'Eng. Ahmed Samir',
      email: 'ahmed.samir@tolab.edu',
      title: 'Assistant',
      department: 'Information Systems',
      subjects: 4,
      status: 'active',
    ),
    StaffMember(
      id: 'SF-203',
      name: 'Dr. Reem Fawzy',
      email: 'reem.fawzy@tolab.edu',
      title: 'Doctor',
      department: 'Engineering',
      subjects: 2,
      status: 'blocked',
    ),
  ];

  List<StaffAdminRecord> staffDirectory() => [
    _staffRecord(
      id: 'DOC-401',
      fullName: 'Dr. Hadeer Salah',
      email: 'hadeer.salah@tolab.edu',
      employeeId: 'FCI-D-401',
      role: 'Doctor',
      doctorType: 'Internal faculty doctor',
      department: 'Computer Science',
      status: 'Active',
      accountCreationStatus: 'Provisioned',
      roleSummary: 'Leads Advanced Algorithms and student progress review.',
      recentActivity: 'Published lecture pack and reviewed task submissions.',
      createdAtLabel: 'Jan 05, 2026',
      lastActiveLabel: '10 minutes ago',
      attendanceRate: 96,
      engagementRate: 91,
      lecturesUploaded: 18,
      tasksCreated: 9,
      postsCreated: 22,
      uploadsCount: 31,
      scheduleUpdates: 5,
      subjects: const [
        StaffSubjectAssignment(
          code: 'CS401',
          title: 'Advanced Algorithms',
          section: 'Lecture hall A',
          lectures: 10,
          tasks: 5,
          posts: 11,
          uploads: 16,
          engagementRate: 92,
          status: 'Healthy',
        ),
        StaffSubjectAssignment(
          code: 'CS404',
          title: 'Compiler Design',
          section: 'Lecture hall C',
          lectures: 8,
          tasks: 4,
          posts: 11,
          uploads: 15,
          engagementRate: 88,
          status: 'Strong',
        ),
      ],
      permissionGroups: _permissionGroups(
        canViewStudentProgress: true,
        canUpdateSchedule: true,
        canManageSubjectContent: true,
      ),
      attendanceTrend: _metricTrend([95, 96, 97, 94, 96, 98, 96]),
      engagementTrend: _metricTrend([82, 86, 88, 89, 91, 93, 91]),
      timeline: const [
        StaffTimelineEvent(
          title: 'Lecture package uploaded',
          subtitle: 'Advanced Algorithms week 8 assets were synced successfully.',
          timeLabel: 'Today, 09:14',
          emphasis: 'strong',
        ),
        StaffTimelineEvent(
          title: 'Task due date adjusted',
          subtitle: 'Extended section task deadline after department review.',
          timeLabel: 'Yesterday',
          emphasis: 'normal',
        ),
        StaffTimelineEvent(
          title: 'Attendance checkpoint completed',
          subtitle: 'Presence records stayed above the faculty target line.',
          timeLabel: '2 days ago',
          emphasis: 'strong',
        ),
      ],
    ),
    _staffRecord(
      id: 'DOC-412',
      fullName: 'Dr. Mostafa Nader',
      email: 'mostafa.nader@tolab.edu',
      employeeId: 'FCI-D-412',
      role: 'Doctor',
      doctorType: 'Delegated / external doctor',
      department: 'Information Systems',
      status: 'Active',
      accountCreationStatus: 'Provisioned',
      roleSummary: 'Owns Enterprise Systems delivery and delegated schedule blocks.',
      recentActivity: 'Posted case-study material and updated office-hour schedule.',
      createdAtLabel: 'Feb 12, 2026',
      lastActiveLabel: '1 hour ago',
      attendanceRate: 84,
      engagementRate: 79,
      lecturesUploaded: 12,
      tasksCreated: 6,
      postsCreated: 13,
      uploadsCount: 17,
      scheduleUpdates: 8,
      subjects: const [
        StaffSubjectAssignment(
          code: 'IS305',
          title: 'Enterprise Systems',
          section: 'Hybrid cohort B',
          lectures: 7,
          tasks: 3,
          posts: 8,
          uploads: 10,
          engagementRate: 81,
          status: 'On track',
        ),
        StaffSubjectAssignment(
          code: 'IS312',
          title: 'Business Intelligence',
          section: 'Lecture hall D',
          lectures: 5,
          tasks: 3,
          posts: 5,
          uploads: 7,
          engagementRate: 76,
          status: 'Monitor',
        ),
      ],
      permissionGroups: _permissionGroups(
        canViewStudentProgress: true,
        canUpdateSchedule: true,
        canManageSubjectContent: true,
        canModeratePosts: false,
      ),
      attendanceTrend: _metricTrend([78, 82, 83, 86, 85, 84, 84]),
      engagementTrend: _metricTrend([70, 72, 74, 77, 79, 80, 79]),
      timeline: const [
        StaffTimelineEvent(
          title: 'Delegated account verified',
          subtitle: 'External contract details were synced with faculty admin.',
          timeLabel: 'Today, 08:10',
          emphasis: 'normal',
        ),
        StaffTimelineEvent(
          title: 'Schedule override requested',
          subtitle: 'Updated lecture slot pending final timetable review.',
          timeLabel: 'Yesterday',
          emphasis: 'attention',
        ),
        StaffTimelineEvent(
          title: 'Community posts reviewed',
          subtitle: 'Three course updates were published to the IS305 stream.',
          timeLabel: '3 days ago',
          emphasis: 'normal',
        ),
      ],
    ),
    _staffRecord(
      id: 'DOC-425',
      fullName: 'Dr. Reem Fawzy',
      email: 'reem.fawzy@tolab.edu',
      employeeId: 'ENG-D-425',
      role: 'Doctor',
      doctorType: 'Internal faculty doctor',
      department: 'Engineering',
      status: 'Inactive',
      accountCreationStatus: 'Under review',
      roleSummary: 'Engineering doctor with limited current semester delivery.',
      recentActivity: 'Account paused pending renewed teaching allocation.',
      createdAtLabel: 'Dec 20, 2025',
      lastActiveLabel: '4 days ago',
      attendanceRate: 62,
      engagementRate: 58,
      lecturesUploaded: 4,
      tasksCreated: 2,
      postsCreated: 3,
      uploadsCount: 5,
      scheduleUpdates: 1,
      subjects: const [
        StaffSubjectAssignment(
          code: 'ENG210',
          title: 'Thermodynamics',
          section: 'Section E2',
          lectures: 2,
          tasks: 1,
          posts: 2,
          uploads: 3,
          engagementRate: 59,
          status: 'Needs follow-up',
        ),
        StaffSubjectAssignment(
          code: 'ENG315',
          title: 'Control Systems',
          section: 'Lab C1',
          lectures: 2,
          tasks: 1,
          posts: 1,
          uploads: 2,
          engagementRate: 57,
          status: 'At risk',
        ),
      ],
      permissionGroups: _permissionGroups(
        canViewStudentProgress: false,
        canUpdateSchedule: false,
        canManageSubjectContent: false,
        canModeratePosts: false,
      ),
      attendanceTrend: _metricTrend([74, 70, 68, 66, 64, 63, 62]),
      engagementTrend: _metricTrend([66, 64, 63, 61, 60, 58, 58]),
      timeline: const [
        StaffTimelineEvent(
          title: 'Account sent for review',
          subtitle: 'Access scope is waiting for department head confirmation.',
          timeLabel: 'Today, 11:40',
          emphasis: 'critical',
        ),
        StaffTimelineEvent(
          title: 'Attendance threshold missed',
          subtitle: 'Presence dipped below the preferred control range.',
          timeLabel: '2 days ago',
          emphasis: 'critical',
        ),
        StaffTimelineEvent(
          title: 'Content output slowed',
          subtitle: 'No new lecture materials were uploaded this week.',
          timeLabel: '4 days ago',
          emphasis: 'attention',
        ),
      ],
    ),
    _staffRecord(
      id: 'DOC-437',
      fullName: 'Dr. Salma Adel',
      email: 'salma.adel@tolab.edu',
      employeeId: 'FCI-D-437',
      role: 'Doctor',
      doctorType: 'Delegated / external doctor',
      department: 'Computer Science',
      status: 'Active',
      accountCreationStatus: 'Invite pending',
      roleSummary: 'Delegated doctor covering AI electives and blended labs.',
      recentActivity: 'Accepted subject assignment but has pending community permissions.',
      createdAtLabel: 'Mar 02, 2026',
      lastActiveLabel: '3 hours ago',
      attendanceRate: 77,
      engagementRate: 73,
      lecturesUploaded: 9,
      tasksCreated: 5,
      postsCreated: 7,
      uploadsCount: 12,
      scheduleUpdates: 2,
      subjects: const [
        StaffSubjectAssignment(
          code: 'CS470',
          title: 'Applied AI',
          section: 'Lecture hall F',
          lectures: 5,
          tasks: 3,
          posts: 4,
          uploads: 7,
          engagementRate: 75,
          status: 'Monitor',
        ),
        StaffSubjectAssignment(
          code: 'CS473',
          title: 'Neural Networks',
          section: 'Lab B4',
          lectures: 4,
          tasks: 2,
          posts: 3,
          uploads: 5,
          engagementRate: 72,
          status: 'On track',
        ),
      ],
      permissionGroups: _permissionGroups(
        canViewStudentProgress: false,
        canUpdateSchedule: false,
        canManageSubjectContent: true,
      ),
      attendanceTrend: _metricTrend([72, 74, 75, 76, 78, 79, 77]),
      engagementTrend: _metricTrend([68, 69, 70, 72, 74, 75, 73]),
      timeline: const [
        StaffTimelineEvent(
          title: 'Account invitation pending',
          subtitle: 'Final activation email has not been accepted yet.',
          timeLabel: 'Today, 07:30',
          emphasis: 'attention',
        ),
        StaffTimelineEvent(
          title: 'Lecture content uploaded',
          subtitle: 'AI elective materials were added to both assigned subjects.',
          timeLabel: 'Yesterday',
          emphasis: 'normal',
        ),
        StaffTimelineEvent(
          title: 'Permissions review opened',
          subtitle: 'Community moderation scope is still awaiting approval.',
          timeLabel: '3 days ago',
          emphasis: 'attention',
        ),
      ],
    ),
    _staffRecord(
      id: 'TA-501',
      fullName: 'Eng. Ahmed Samir',
      email: 'ahmed.samir@tolab.edu',
      employeeId: 'IS-TA-501',
      role: 'Assistant',
      doctorType: null,
      department: 'Information Systems',
      status: 'Active',
      accountCreationStatus: 'Provisioned',
      roleSummary: 'Primary section coordinator for enterprise labs.',
      recentActivity: 'Closed student questions and uploaded lab support sheets.',
      createdAtLabel: 'Jan 18, 2026',
      lastActiveLabel: '18 minutes ago',
      attendanceRate: 93,
      engagementRate: 88,
      lecturesUploaded: 0,
      tasksCreated: 7,
      postsCreated: 18,
      uploadsCount: 26,
      scheduleUpdates: 4,
      subjects: const [
        StaffSubjectAssignment(
          code: 'IS305',
          title: 'Enterprise Systems',
          section: 'Section B1',
          lectures: 0,
          tasks: 4,
          posts: 10,
          uploads: 14,
          engagementRate: 89,
          status: 'Strong',
        ),
        StaffSubjectAssignment(
          code: 'IS204',
          title: 'Database Systems',
          section: 'Lab A2',
          lectures: 0,
          tasks: 3,
          posts: 8,
          uploads: 12,
          engagementRate: 87,
          status: 'Healthy',
        ),
      ],
      permissionGroups: _permissionGroups(
        canCreateLectures: false,
        canUploadLectureFiles: false,
        canViewStudentProgress: true,
        canUpdateSchedule: false,
        canManageSubjectContent: true,
      ),
      attendanceTrend: _metricTrend([89, 90, 92, 94, 93, 95, 93]),
      engagementTrend: _metricTrend([80, 82, 84, 87, 88, 90, 88]),
      timeline: const [
        StaffTimelineEvent(
          title: 'Section resources uploaded',
          subtitle: 'Database Systems support materials were added to the lab area.',
          timeLabel: 'Today, 10:05',
          emphasis: 'strong',
        ),
        StaffTimelineEvent(
          title: 'Student questions resolved',
          subtitle: 'Eight forum items were answered across assigned subjects.',
          timeLabel: 'Yesterday',
          emphasis: 'normal',
        ),
        StaffTimelineEvent(
          title: 'Attendance logged',
          subtitle: 'Assistant presence stayed above the target band all week.',
          timeLabel: '2 days ago',
          emphasis: 'strong',
        ),
      ],
    ),
    _staffRecord(
      id: 'TA-512',
      fullName: 'Eng. Menna Wael',
      email: 'menna.wael@tolab.edu',
      employeeId: 'FCI-TA-512',
      role: 'Assistant',
      doctorType: null,
      department: 'Computer Science',
      status: 'Active',
      accountCreationStatus: 'Provisioned',
      roleSummary: 'Teaching assistant supporting operating systems sections.',
      recentActivity: 'Uploaded lab notes and monitored task discussion threads.',
      createdAtLabel: 'Jan 24, 2026',
      lastActiveLabel: '42 minutes ago',
      attendanceRate: 86,
      engagementRate: 81,
      lecturesUploaded: 0,
      tasksCreated: 6,
      postsCreated: 15,
      uploadsCount: 21,
      scheduleUpdates: 2,
      subjects: const [
        StaffSubjectAssignment(
          code: 'CS330',
          title: 'Operating Systems',
          section: 'Lab D3',
          lectures: 0,
          tasks: 4,
          posts: 9,
          uploads: 12,
          engagementRate: 83,
          status: 'Healthy',
        ),
        StaffSubjectAssignment(
          code: 'CS250',
          title: 'Data Structures',
          section: 'Section A1',
          lectures: 0,
          tasks: 2,
          posts: 6,
          uploads: 9,
          engagementRate: 78,
          status: 'On track',
        ),
      ],
      permissionGroups: _permissionGroups(
        canCreateLectures: false,
        canUploadLectureFiles: false,
        canViewStudentProgress: false,
        canUpdateSchedule: false,
        canManageSubjectContent: true,
      ),
      attendanceTrend: _metricTrend([81, 82, 84, 85, 86, 87, 86]),
      engagementTrend: _metricTrend([75, 77, 78, 80, 82, 83, 81]),
      timeline: const [
        StaffTimelineEvent(
          title: 'Section content refreshed',
          subtitle: 'Operating Systems lab tasks were updated with new hints.',
          timeLabel: 'Today, 08:42',
          emphasis: 'normal',
        ),
        StaffTimelineEvent(
          title: 'Upload queue completed',
          subtitle: 'All support PDFs were synchronized successfully.',
          timeLabel: 'Yesterday',
          emphasis: 'strong',
        ),
        StaffTimelineEvent(
          title: 'Schedule update declined',
          subtitle: 'Requested lab swap needs doctor-level approval first.',
          timeLabel: '4 days ago',
          emphasis: 'attention',
        ),
      ],
    ),
    _staffRecord(
      id: 'TA-526',
      fullName: 'Eng. Nourhan Essam',
      email: 'nourhan.essam@tolab.edu',
      employeeId: 'ENG-TA-526',
      role: 'Assistant',
      doctorType: null,
      department: 'Engineering',
      status: 'Inactive',
      accountCreationStatus: 'Suspended',
      roleSummary: 'Assistant profile with paused semester access.',
      recentActivity: 'Temporary suspension was applied after attendance review.',
      createdAtLabel: 'Nov 30, 2025',
      lastActiveLabel: '6 days ago',
      attendanceRate: 68,
      engagementRate: 61,
      lecturesUploaded: 0,
      tasksCreated: 2,
      postsCreated: 4,
      uploadsCount: 6,
      scheduleUpdates: 1,
      subjects: const [
        StaffSubjectAssignment(
          code: 'ENG120',
          title: 'Engineering Drawing',
          section: 'Lab E1',
          lectures: 0,
          tasks: 1,
          posts: 2,
          uploads: 3,
          engagementRate: 63,
          status: 'At risk',
        ),
        StaffSubjectAssignment(
          code: 'ENG221',
          title: 'Mechanics',
          section: 'Section M2',
          lectures: 0,
          tasks: 1,
          posts: 2,
          uploads: 3,
          engagementRate: 59,
          status: 'Needs follow-up',
        ),
      ],
      permissionGroups: _permissionGroups(
        canCreateLectures: false,
        canUploadLectureFiles: false,
        canViewStudentProgress: false,
        canUpdateSchedule: false,
        canManageSubjectContent: false,
        canModeratePosts: false,
      ),
      attendanceTrend: _metricTrend([76, 74, 72, 70, 69, 68, 68]),
      engagementTrend: _metricTrend([69, 67, 65, 64, 63, 61, 61]),
      timeline: const [
        StaffTimelineEvent(
          title: 'Assistant access suspended',
          subtitle: 'Profile is paused until faculty monitoring review closes.',
          timeLabel: 'Today, 12:15',
          emphasis: 'critical',
        ),
        StaffTimelineEvent(
          title: 'Attendance warning raised',
          subtitle: 'Presence score stayed below the expected line for two weeks.',
          timeLabel: 'Yesterday',
          emphasis: 'critical',
        ),
        StaffTimelineEvent(
          title: 'Content permissions restricted',
          subtitle: 'Upload and posting scope were reduced automatically.',
          timeLabel: '3 days ago',
          emphasis: 'attention',
        ),
      ],
    ),
    _staffRecord(
      id: 'TA-538',
      fullName: 'Eng. Omar Adel',
      email: 'omar.adel.staff@tolab.edu',
      employeeId: 'FCI-TA-538',
      role: 'Assistant',
      doctorType: null,
      department: 'Computer Science',
      status: 'Active',
      accountCreationStatus: 'Provisioned',
      roleSummary: 'Assistant handling community follow-up and material uploads.',
      recentActivity: 'Managed course posts and prepared this week lab sheets.',
      createdAtLabel: 'Feb 05, 2026',
      lastActiveLabel: '27 minutes ago',
      attendanceRate: 90,
      engagementRate: 85,
      lecturesUploaded: 0,
      tasksCreated: 5,
      postsCreated: 20,
      uploadsCount: 19,
      scheduleUpdates: 3,
      subjects: const [
        StaffSubjectAssignment(
          code: 'CS290',
          title: 'Web Engineering',
          section: 'Lab W1',
          lectures: 0,
          tasks: 3,
          posts: 12,
          uploads: 11,
          engagementRate: 86,
          status: 'Strong',
        ),
        StaffSubjectAssignment(
          code: 'CS315',
          title: 'Software Testing',
          section: 'Section T2',
          lectures: 0,
          tasks: 2,
          posts: 8,
          uploads: 8,
          engagementRate: 84,
          status: 'Healthy',
        ),
      ],
      permissionGroups: _permissionGroups(
        canCreateLectures: false,
        canUploadLectureFiles: false,
        canViewStudentProgress: true,
        canUpdateSchedule: true,
        canManageSubjectContent: true,
      ),
      attendanceTrend: _metricTrend([86, 87, 89, 90, 90, 91, 90]),
      engagementTrend: _metricTrend([79, 80, 82, 84, 86, 86, 85]),
      timeline: const [
        StaffTimelineEvent(
          title: 'Course post moderation complete',
          subtitle: 'Discussion posts were triaged and pinned for students.',
          timeLabel: 'Today, 09:55',
          emphasis: 'strong',
        ),
        StaffTimelineEvent(
          title: 'Task instructions uploaded',
          subtitle: 'New testing-lab instructions were shared with both sections.',
          timeLabel: 'Yesterday',
          emphasis: 'normal',
        ),
        StaffTimelineEvent(
          title: 'Schedule patch approved',
          subtitle: 'Assistant received permission to update one lab session slot.',
          timeLabel: '2 days ago',
          emphasis: 'normal',
        ),
      ],
    ),
  ];

  List<DepartmentModel> departments() => const [
    DepartmentModel(
      id: 'DEP-1',
      name: 'Computer Science',
      code: 'CS',
      head: 'Dr. Eman Adel',
      status: 'active',
      studentsCount: 3120,
    ),
    DepartmentModel(
      id: 'DEP-2',
      name: 'Information Systems',
      code: 'IS',
      head: 'Dr. Nader Mostafa',
      status: 'active',
      studentsCount: 2540,
    ),
  ];

  List<SectionModel> sections() => const [
    SectionModel(
      id: 'SEC-1',
      name: 'CS-4A',
      department: 'Computer Science',
      year: '2025/2026',
      semester: 'Spring',
      status: 'active',
    ),
    SectionModel(
      id: 'SEC-2',
      name: 'IS-3B',
      department: 'Information Systems',
      year: '2025/2026',
      semester: 'Spring',
      status: 'active',
    ),
  ];

  List<SubjectModel> subjects() => const [
    SubjectModel(
      id: 'SUB-1',
      code: 'CS401',
      name: 'Advanced Algorithms',
      department: 'Computer Science',
      credits: 3,
      status: 'active',
    ),
    SubjectModel(
      id: 'SUB-2',
      code: 'IS305',
      name: 'Enterprise Systems',
      department: 'Information Systems',
      credits: 2,
      status: 'active',
    ),
  ];

  List<CourseOfferingModel> courseOfferings() => const [
    CourseOfferingModel(
      id: 'OFF-1',
      subjectCode: 'CS401',
      subjectName: 'Advanced Algorithms',
      sectionName: 'CS-4A',
      doctorName: 'Dr. Hadeer Salah',
      assistantName: 'Eng. Ahmed Samir',
      semester: 'Spring 2026',
      enrolled: 88,
      capacity: 100,
      status: 'active',
    ),
    CourseOfferingModel(
      id: 'OFF-2',
      subjectCode: 'IS305',
      subjectName: 'Enterprise Systems',
      sectionName: 'IS-3B',
      doctorName: 'Dr. Reem Fawzy',
      assistantName: 'Eng. Ahmed Samir',
      semester: 'Spring 2026',
      enrolled: 76,
      capacity: 80,
      status: 'pending',
    ),
  ];

  List<EnrollmentRecord> enrollments() => const [
    EnrollmentRecord(
      id: 'ENR-1',
      studentName: 'Omar Adel',
      subjectName: 'Advanced Algorithms',
      department: 'Computer Science',
      level: 'Level 4',
      status: 'active',
    ),
    EnrollmentRecord(
      id: 'ENR-2',
      studentName: 'Mariam Tarek',
      subjectName: 'Enterprise Systems',
      department: 'Information Systems',
      level: 'Level 3',
      status: 'active',
    ),
  ];

  List<ContentItem> contentItems() => const [
    ContentItem(
      id: 'CNT-1',
      courseTitle: 'Advanced Algorithms',
      type: 'Lecture',
      title: 'Greedy Optimization Patterns',
      status: 'published',
      attachments: 3,
      dueDateLabel: 'Apr 14, 2026',
    ),
    ContentItem(
      id: 'CNT-2',
      courseTitle: 'Enterprise Systems',
      type: 'Quiz',
      title: 'Week 5 Assessment',
      status: 'scheduled',
      attachments: 1,
      dueDateLabel: 'Apr 20, 2026',
    ),
  ];

  List<UploadItem> uploads() => const [
    UploadItem(
      id: 'UP-1',
      name: 'semester-schedule.xlsx',
      sizeLabel: '2.8 MB',
      progress: 1,
      status: 'completed',
      mimeType: 'application/vnd.ms-excel',
    ),
    UploadItem(
      id: 'UP-2',
      name: 'lecture-assets.zip',
      sizeLabel: '84 MB',
      progress: .54,
      status: 'uploading',
      mimeType: 'application/zip',
    ),
  ];

  List<ScheduleEventModel> scheduleEvents() {
    final now = DateTime.now();
    return [
      ScheduleEventModel(
        id: 'EV-1',
        title: 'Lecture 08',
        course: 'Advanced Algorithms',
        instructor: 'Dr. Hadeer Salah',
        location: 'Hall B12',
        type: 'lecture',
        status: 'planned',
        start: DateTime(now.year, now.month, now.day, 9),
        end: DateTime(now.year, now.month, now.day, 11),
        color: AppColors.primary,
      ),
      ScheduleEventModel(
        id: 'EV-2',
        title: 'Section Review',
        course: 'Enterprise Systems',
        instructor: 'Eng. Ahmed Samir',
        location: 'Lab C3',
        type: 'section',
        status: 'completed',
        start: DateTime(now.year, now.month, now.day + 1, 12),
        end: DateTime(now.year, now.month, now.day + 1, 14),
        color: AppColors.secondary,
      ),
      ScheduleEventModel(
        id: 'EV-3',
        title: 'Midterm Exam',
        course: 'Operating Systems',
        instructor: 'Dr. Reem Fawzy',
        location: 'Main Auditorium',
        type: 'exam',
        status: 'planned',
        start: DateTime(now.year, now.month, now.day + 3, 10),
        end: DateTime(now.year, now.month, now.day + 3, 12),
        color: AppColors.warning,
      ),
    ];
  }

  List<AdminNotification> notifications() => const [
    AdminNotification(
      id: 'NT-1',
      title: 'Semester registration deadline',
      body: 'Broadcast scheduled for all level 3 students.',
      category: 'broadcast',
      createdAtLabel: 'Today, 09:20',
      isRead: false,
    ),
    AdminNotification(
      id: 'NT-2',
      title: 'Upload policy updated',
      body: 'Maximum file size raised to 250 MB for administrators.',
      category: 'system',
      createdAtLabel: 'Yesterday',
      isRead: true,
    ),
  ];

  List<ModerationItem> moderationItems() => const [
    ModerationItem(
      id: 'MOD-1',
      type: 'Post',
      author: 'Mahmoud Ashraf',
      groupName: 'CS-4A',
      preview: 'Thread contains duplicated external links.',
      reportsCount: 4,
      status: 'flagged',
      createdAtLabel: '18 min ago',
    ),
    ModerationItem(
      id: 'MOD-2',
      type: 'Message',
      author: 'Sara Emad',
      groupName: 'IS-3B',
      preview: 'Potential harassment phrase detected by policy filter.',
      reportsCount: 2,
      status: 'pending',
      createdAtLabel: '1h ago',
    ),
  ];

  List<RolePermission> roles() => const [
    RolePermission(
      id: 'ROLE-1',
      role: 'Super Admin',
      members: 3,
      permissions: {
        'manage_users': true,
        'manage_schedule': true,
        'moderate_groups': true,
        'broadcast_notifications': true,
      },
    ),
    RolePermission(
      id: 'ROLE-2',
      role: 'Moderator',
      members: 8,
      permissions: {
        'manage_users': false,
        'manage_schedule': false,
        'moderate_groups': true,
        'broadcast_notifications': false,
      },
    ),
  ];

  SettingsBundle settings() => const SettingsBundle(
    themeMode: ThemeMode.light,
    localeCode: 'en',
    pushEnabled: true,
    desktopAlertsEnabled: true,
    auditLoggingEnabled: true,
    sessionTimeoutMinutes: 30,
    uploadLimitMb: 250,
  );

  StaffAdminRecord _staffRecord({
    required String id,
    required String fullName,
    required String email,
    required String employeeId,
    required String role,
    required String? doctorType,
    required String department,
    required String status,
    required String accountCreationStatus,
    required String roleSummary,
    required String recentActivity,
    required String createdAtLabel,
    required String lastActiveLabel,
    required double attendanceRate,
    required double engagementRate,
    required int lecturesUploaded,
    required int tasksCreated,
    required int postsCreated,
    required int uploadsCount,
    required int scheduleUpdates,
    required List<StaffSubjectAssignment> subjects,
    required List<StaffPermissionGroup> permissionGroups,
    required List<StaffTimelineEvent> timeline,
    required List<StaffMetricPoint> attendanceTrend,
    required List<StaffMetricPoint> engagementTrend,
  }) {
    final totalPermissions = permissionGroups.fold<int>(
      0,
      (sum, group) => sum + group.permissions.length,
    );
    final enabledPermissions = permissionGroups.fold<int>(
      0,
      (sum, group) =>
          sum +
          group.permissions.where((permission) => permission.enabled).length,
    );

    return StaffAdminRecord(
      id: id,
      fullName: fullName,
      email: email,
      employeeId: employeeId,
      role: role,
      doctorType: doctorType,
      department: department,
      status: status,
      accountCreationStatus: accountCreationStatus,
      roleSummary: roleSummary,
      recentActivity: recentActivity,
      createdAtLabel: createdAtLabel,
      lastActiveLabel: lastActiveLabel,
      attendanceRate: attendanceRate,
      engagementRate: engagementRate,
      permissionCoverage: totalPermissions == 0
          ? 0
          : (enabledPermissions / totalPermissions) * 100,
      subjectsAssigned: subjects.length,
      lecturesUploaded: lecturesUploaded,
      tasksCreated: tasksCreated,
      postsCreated: postsCreated,
      uploadsCount: uploadsCount,
      scheduleUpdates: scheduleUpdates,
      subjects: subjects,
      permissionGroups: permissionGroups,
      timeline: timeline,
      attendanceTrend: attendanceTrend,
      engagementTrend: engagementTrend,
    );
  }

  List<StaffPermissionGroup> _permissionGroups({
    bool canCreateLectures = true,
    bool canUploadLectureFiles = true,
    bool canManageSections = true,
    bool canUploadTasks = true,
    bool canSetTaskDates = true,
    bool canViewStudentProgress = false,
    bool canPostInCommunity = true,
    bool canModeratePosts = true,
    bool canManageSubjectContent = false,
    bool canUpdateSchedule = false,
    bool canUploadMaterials = true,
    bool canAcademicInteract = true,
  }) {
    return [
      StaffPermissionGroup(
        id: 'content',
        title: 'Content delivery',
        subtitle: 'Lectures, sections, files, and structured academic content.',
        icon: Icons.play_lesson_outlined,
        permissions: [
          StaffPermission(
            id: 'create_lectures',
            title: 'Create lectures',
            description: 'Publish lecture entries and structure class delivery.',
            enabled: canCreateLectures,
          ),
          StaffPermission(
            id: 'upload_lecture_files',
            title: 'Upload lecture files',
            description: 'Attach slides, recordings, and lecture materials.',
            enabled: canUploadLectureFiles,
          ),
          StaffPermission(
            id: 'manage_sections',
            title: 'Create sections',
            description: 'Open section sessions and keep related content updated.',
            enabled: canManageSections,
          ),
        ],
      ),
      StaffPermissionGroup(
        id: 'assessment',
        title: 'Assessment and student follow-up',
        subtitle: 'Tasks, due dates, and student academic visibility.',
        icon: Icons.assignment_turned_in_outlined,
        permissions: [
          StaffPermission(
            id: 'upload_tasks',
            title: 'Upload tasks',
            description: 'Create tasks and attach assessment instructions.',
            enabled: canUploadTasks,
          ),
          StaffPermission(
            id: 'set_due_dates',
            title: 'Add task due dates',
            description: 'Define deadlines and open submission windows.',
            enabled: canSetTaskDates,
          ),
          StaffPermission(
            id: 'view_student_progress',
            title: 'View student progress',
            description: 'See progress indicators when academic review allows it.',
            enabled: canViewStudentProgress,
          ),
        ],
      ),
      StaffPermissionGroup(
        id: 'community',
        title: 'Subject community and moderation',
        subtitle: 'Posts, announcements, and academic interaction with students.',
        icon: Icons.forum_outlined,
        permissions: [
          StaffPermission(
            id: 'post_in_course',
            title: 'Post in course community',
            description: 'Publish academic notices and answer course questions.',
            enabled: canPostInCommunity,
          ),
          StaffPermission(
            id: 'manage_subject_posts',
            title: 'Manage subject posts',
            description: 'Edit, pin, or moderate subject-related posts.',
            enabled: canModeratePosts,
          ),
          StaffPermission(
            id: 'academic_interaction',
            title: 'Interact with students academically',
            description: 'Respond to academic questions and follow up on feedback.',
            enabled: canAcademicInteract,
          ),
        ],
      ),
      StaffPermissionGroup(
        id: 'operations',
        title: 'Subject operations',
        subtitle: 'Materials, schedule control, and content governance.',
        icon: Icons.admin_panel_settings_outlined,
        permissions: [
          StaffPermission(
            id: 'manage_subject_content',
            title: 'Manage subject content',
            description: 'Edit published materials and subject content structure.',
            enabled: canManageSubjectContent,
          ),
          StaffPermission(
            id: 'update_schedule',
            title: 'Update schedule',
            description: 'Adjust class timing when department approval exists.',
            enabled: canUpdateSchedule,
          ),
          StaffPermission(
            id: 'upload_materials',
            title: 'Upload materials',
            description: 'Add books, sheets, and supplemental academic files.',
            enabled: canUploadMaterials,
          ),
        ],
      ),
    ];
  }

  List<StaffMetricPoint> _metricTrend(List<double> values) {
    const labels = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'];
    return List<StaffMetricPoint>.generate(
      values.length,
      (index) => StaffMetricPoint(
        label: labels[index.clamp(0, labels.length - 1)],
        value: values[index],
      ),
    );
  }
}
