import '../models/student_admin_models.dart';

class StudentsRepository {
  StudentsRepository();

  Future<List<StudentAdminRecord>> fetchStudents() async {
    await Future<void>.delayed(const Duration(milliseconds: 320));
    return _mockStudents;
  }
}

final List<StudentAdminRecord> _mockStudents = [
  _student(
    id: 'ST-2401',
    nationalId: '30209142104561',
    fullName: 'Omar Adel',
    email: 'omar.adel@tolab.edu',
    phone: '+20 101 778 2201',
    department: 'Computer Science',
    batch: '2022',
    academicLevel: 'Level 4',
    section: 'CS-4A',
    status: 'Active',
    advisorName: 'Dr. Hadeer Salah',
    termGpa: 3.78,
    cumulativeGpa: 3.82,
    attendanceRate: 94,
    subjectActivityRate: 89,
    doctorInteractionRate: 83,
    earnedCreditHours: 118,
    remainingCreditHours: 18,
    quizzesTaken: 12,
    examsTaken: 4,
    lecturesAttended: 43,
    totalLectures: 46,
    appSessionsThisWeek: 11,
    messagesWithDoctors: 8,
    lastActiveLabel: '12 min ago',
    registrationWindowLabel: 'Sent for Spring 2026',
    registrationAccessSent: true,
    overallGrade: 'A',
    permissions: [
      _permission(
        'Course registration',
        'Allowed to submit registration requests',
        true,
      ),
      _permission('Doctor messaging', 'May contact assigned instructors', true),
      _permission(
        'Financial hold override',
        'Temporarily disabled until finance sync',
        false,
      ),
    ],
    activeCourses: [
      _course(
        'CS401',
        'Advanced Algorithms',
        'Dr. Hadeer Salah',
        3,
        0.86,
        95,
        91,
        'Strong',
      ),
      _course(
        'CS402',
        'Distributed Systems',
        'Dr. Salma Nabil',
        3,
        0.74,
        92,
        88,
        'Healthy',
      ),
      _course(
        'CS404',
        'Data Mining',
        'Dr. Dalia Hussein',
        2,
        0.67,
        90,
        84,
        'Healthy',
      ),
    ],
    completedCourses: [
      _course(
        'CS303',
        'Operating Systems',
        'Dr. Reem Fawzy',
        3,
        1,
        93,
        90,
        'Completed',
      ),
      _course(
        'CS305',
        'Database Systems',
        'Dr. Ahmed Samir',
        3,
        1,
        96,
        94,
        'Completed',
      ),
    ],
    timeline: [
      _event(
        'Completed registration review',
        'Advisor validated current elective plan',
        'Today, 09:14',
        'registration',
        'strong',
      ),
      _event(
        'Doctor interaction spike',
        '3 office-hour messages with Distributed Systems doctor',
        'Yesterday',
        'interaction',
        'good',
      ),
      _event(
        'Attendance check passed',
        'No recent absence alerts across active subjects',
        '2 days ago',
        'attendance',
        'good',
      ),
    ],
    engagementTrend: const [
      StudentTrendPoint(label: 'Jan', value: 72),
      StudentTrendPoint(label: 'Feb', value: 78),
      StudentTrendPoint(label: 'Mar', value: 81),
      StudentTrendPoint(label: 'Apr', value: 84),
      StudentTrendPoint(label: 'May', value: 87),
      StudentTrendPoint(label: 'Jun', value: 89),
    ],
  ),
  _student(
    id: 'ST-2408',
    nationalId: '30301051200433',
    fullName: 'Mariam Tarek',
    email: 'mariam.tarek@tolab.edu',
    phone: '+20 114 921 5433',
    department: 'Information Systems',
    batch: '2023',
    academicLevel: 'Level 3',
    section: 'IS-3B',
    status: 'Active',
    advisorName: 'Dr. Nader Mostafa',
    termGpa: 3.93,
    cumulativeGpa: 3.89,
    attendanceRate: 96,
    subjectActivityRate: 92,
    doctorInteractionRate: 78,
    earnedCreditHours: 86,
    remainingCreditHours: 50,
    quizzesTaken: 10,
    examsTaken: 3,
    lecturesAttended: 38,
    totalLectures: 40,
    appSessionsThisWeek: 14,
    messagesWithDoctors: 6,
    lastActiveLabel: '4 min ago',
    registrationWindowLabel: 'Ready to send',
    registrationAccessSent: false,
    overallGrade: 'A',
    permissions: [
      _permission(
        'Course registration',
        'Registration access not yet sent for next term',
        false,
      ),
      _permission(
        'Doctor messaging',
        'Student can contact assigned instructors',
        true,
      ),
      _permission(
        'Profile edits',
        'Editable contact data and optional documents',
        true,
      ),
    ],
    activeCourses: [
      _course(
        'IS305',
        'Enterprise Systems',
        'Dr. Nader Mostafa',
        3,
        0.91,
        97,
        95,
        'Strong',
      ),
      _course(
        'IS307',
        'Business Intelligence',
        'Dr. Rania Farid',
        3,
        0.84,
        94,
        90,
        'Strong',
      ),
      _course(
        'IS311',
        'Systems Analysis',
        'Dr. Ayman Khaled',
        2,
        0.79,
        96,
        88,
        'Healthy',
      ),
    ],
    completedCourses: [
      _course(
        'IS204',
        'E-Commerce',
        'Dr. Hossam Ali',
        3,
        1,
        95,
        93,
        'Completed',
      ),
      _course(
        'IS210',
        'Data Warehousing',
        'Dr. Rania Farid',
        3,
        1,
        98,
        96,
        'Completed',
      ),
    ],
    timeline: [
      _event(
        'Submitted lab milestone',
        'Business Intelligence dashboard prototype reviewed',
        'Today, 11:22',
        'academic',
        'strong',
      ),
      _event(
        'Registration access pending',
        'Eligible for batch send once department approves seats',
        'Yesterday',
        'registration',
        'attention',
      ),
      _event(
        'Attendance streak',
        '14 consecutive sessions with full attendance',
        '3 days ago',
        'attendance',
        'good',
      ),
    ],
    engagementTrend: const [
      StudentTrendPoint(label: 'Jan', value: 74),
      StudentTrendPoint(label: 'Feb', value: 76),
      StudentTrendPoint(label: 'Mar', value: 82),
      StudentTrendPoint(label: 'Apr', value: 88),
      StudentTrendPoint(label: 'May', value: 91),
      StudentTrendPoint(label: 'Jun', value: 93),
    ],
  ),
  _student(
    id: 'ST-2414',
    nationalId: '30112281544780',
    fullName: 'Youssef Ali',
    email: 'youssef.ali@tolab.edu',
    phone: '+20 100 664 1182',
    department: 'Engineering',
    batch: '2024',
    academicLevel: 'Level 2',
    section: 'ENG-2A',
    status: 'Watchlist',
    advisorName: 'Dr. Reem Fawzy',
    termGpa: 2.61,
    cumulativeGpa: 2.48,
    attendanceRate: 72,
    subjectActivityRate: 61,
    doctorInteractionRate: 44,
    earnedCreditHours: 42,
    remainingCreditHours: 94,
    quizzesTaken: 8,
    examsTaken: 2,
    lecturesAttended: 24,
    totalLectures: 33,
    appSessionsThisWeek: 4,
    messagesWithDoctors: 2,
    lastActiveLabel: '5 hours ago',
    registrationWindowLabel: 'Needs advisor intervention',
    registrationAccessSent: false,
    overallGrade: 'C+',
    permissions: [
      _permission(
        'Course registration',
        'Blocked until academic warning is reviewed',
        false,
      ),
      _permission(
        'Doctor messaging',
        'Student may message assigned instructors',
        true,
      ),
      _permission('Assessment appeals', 'Appeal requests still enabled', true),
    ],
    activeCourses: [
      _course(
        'ENG211',
        'Thermodynamics',
        'Dr. Reem Fawzy',
        3,
        0.53,
        69,
        63,
        'Weak',
      ),
      _course(
        'ENG214',
        'Mechanics II',
        'Dr. Basma Adel',
        3,
        0.58,
        74,
        67,
        'Watch',
      ),
      _course(
        'ENG220',
        'Applied Mathematics',
        'Dr. Maha Saad',
        2,
        0.62,
        73,
        70,
        'Watch',
      ),
    ],
    completedCourses: [
      _course(
        'ENG102',
        'Engineering Drawing',
        'Dr. Omar Zaki',
        2,
        1,
        84,
        74,
        'Completed',
      ),
    ],
    timeline: [
      _event(
        'Attendance alert opened',
        'Thermodynamics attendance dropped below 70%',
        'Today, 08:06',
        'attendance',
        'critical',
      ),
      _event(
        'Advisor follow-up requested',
        'Automated watchlist workflow triggered',
        'Yesterday',
        'advising',
        'attention',
      ),
      _event(
        'Low platform engagement',
        'No lecture material opened for 3 days',
        '4 days ago',
        'app',
        'critical',
      ),
    ],
    engagementTrend: const [
      StudentTrendPoint(label: 'Jan', value: 66),
      StudentTrendPoint(label: 'Feb', value: 63),
      StudentTrendPoint(label: 'Mar', value: 61),
      StudentTrendPoint(label: 'Apr', value: 58),
      StudentTrendPoint(label: 'May', value: 55),
      StudentTrendPoint(label: 'Jun', value: 52),
    ],
  ),
  _student(
    id: 'ST-2420',
    nationalId: '30403071233411',
    fullName: 'Salma Nabil',
    email: 'salma.nabil@tolab.edu',
    phone: '+20 102 331 7784',
    department: 'Computer Science',
    batch: '2023',
    academicLevel: 'Level 3',
    section: 'CS-3C',
    status: 'Active',
    advisorName: 'Dr. Eman Adel',
    termGpa: 3.56,
    cumulativeGpa: 3.48,
    attendanceRate: 88,
    subjectActivityRate: 84,
    doctorInteractionRate: 79,
    earnedCreditHours: 82,
    remainingCreditHours: 54,
    quizzesTaken: 11,
    examsTaken: 3,
    lecturesAttended: 35,
    totalLectures: 40,
    appSessionsThisWeek: 9,
    messagesWithDoctors: 5,
    lastActiveLabel: '36 min ago',
    registrationWindowLabel: 'Sent for Spring 2026',
    registrationAccessSent: true,
    overallGrade: 'B+',
    permissions: [
      _permission(
        'Course registration',
        'Registration access already sent',
        true,
      ),
      _permission(
        'Group messaging',
        'May receive department-wide announcements',
        true,
      ),
      _permission('Profile edits', 'Locked during scholarship review', false),
    ],
    activeCourses: [
      _course(
        'CS309',
        'Mobile Development',
        'Dr. Eman Adel',
        3,
        0.82,
        91,
        87,
        'Healthy',
      ),
      _course(
        'CS315',
        'Compiler Design',
        'Dr. Mona Hassan',
        3,
        0.73,
        85,
        83,
        'Healthy',
      ),
      _course(
        'CS317',
        'Theory of Computation',
        'Dr. Hadeer Salah',
        2,
        0.78,
        89,
        85,
        'Healthy',
      ),
    ],
    completedCourses: [
      _course(
        'CS205',
        'Object Oriented Programming',
        'Dr. Ayman Reda',
        3,
        1,
        88,
        89,
        'Completed',
      ),
    ],
    timeline: [
      _event(
        'Doctor feedback received',
        'Compiler Design assignment reviewed with notes',
        'Today, 10:31',
        'interaction',
        'good',
      ),
      _event(
        'Scholarship review in progress',
        'Profile editing temporarily disabled',
        '2 days ago',
        'admin',
        'attention',
      ),
    ],
    engagementTrend: const [
      StudentTrendPoint(label: 'Jan', value: 68),
      StudentTrendPoint(label: 'Feb', value: 71),
      StudentTrendPoint(label: 'Mar', value: 76),
      StudentTrendPoint(label: 'Apr', value: 79),
      StudentTrendPoint(label: 'May', value: 84),
      StudentTrendPoint(label: 'Jun', value: 86),
    ],
  ),
  _student(
    id: 'ST-2429',
    nationalId: '30207011433955',
    fullName: 'Karim Essam',
    email: 'karim.essam@tolab.edu',
    phone: '+20 111 210 4406',
    department: 'Computer Science',
    batch: '2024',
    academicLevel: 'Level 2',
    section: 'CS-2D',
    status: 'Probation',
    advisorName: 'Dr. Dalia Hussein',
    termGpa: 2.34,
    cumulativeGpa: 2.27,
    attendanceRate: 76,
    subjectActivityRate: 58,
    doctorInteractionRate: 51,
    earnedCreditHours: 39,
    remainingCreditHours: 97,
    quizzesTaken: 7,
    examsTaken: 2,
    lecturesAttended: 28,
    totalLectures: 37,
    appSessionsThisWeek: 5,
    messagesWithDoctors: 3,
    lastActiveLabel: '1 day ago',
    registrationWindowLabel: 'Requires probation clearance',
    registrationAccessSent: false,
    overallGrade: 'C',
    permissions: [
      _permission(
        'Course registration',
        'Needs probation approval before activation',
        false,
      ),
      _permission(
        'Doctor messaging',
        'Enabled for academic recovery workflow',
        true,
      ),
      _permission(
        'Activity monitoring',
        'Enhanced monitoring flag applied',
        true,
      ),
    ],
    activeCourses: [
      _course(
        'CS219',
        'Discrete Structures',
        'Dr. Mohamed Ashraf',
        3,
        0.57,
        80,
        66,
        'Watch',
      ),
      _course(
        'CS221',
        'Computer Organization',
        'Dr. Eman Adel',
        3,
        0.49,
        72,
        61,
        'Weak',
      ),
    ],
    completedCourses: [
      _course(
        'CS110',
        'Intro to Programming',
        'Dr. Mona Hassan',
        3,
        1,
        82,
        72,
        'Completed',
      ),
    ],
    timeline: [
      _event(
        'Probation reminder sent',
        'Admin must review before next registration cycle',
        'Today, 07:40',
        'admin',
        'critical',
      ),
      _event(
        'Interaction improved',
        'Two advisor follow-up responses received',
        'Yesterday',
        'interaction',
        'attention',
      ),
    ],
    engagementTrend: const [
      StudentTrendPoint(label: 'Jan', value: 54),
      StudentTrendPoint(label: 'Feb', value: 52),
      StudentTrendPoint(label: 'Mar', value: 56),
      StudentTrendPoint(label: 'Apr', value: 58),
      StudentTrendPoint(label: 'May', value: 60),
      StudentTrendPoint(label: 'Jun', value: 61),
    ],
  ),
  _student(
    id: 'ST-2435',
    nationalId: '30304291645209',
    fullName: 'Farah Mohamed',
    email: 'farah.mohamed@tolab.edu',
    phone: '+20 112 775 3401',
    department: 'Information Systems',
    batch: '2022',
    academicLevel: 'Level 4',
    section: 'IS-4A',
    status: 'Active',
    advisorName: 'Dr. Rania Farid',
    termGpa: 3.44,
    cumulativeGpa: 3.36,
    attendanceRate: 87,
    subjectActivityRate: 80,
    doctorInteractionRate: 72,
    earnedCreditHours: 112,
    remainingCreditHours: 24,
    quizzesTaken: 12,
    examsTaken: 4,
    lecturesAttended: 39,
    totalLectures: 45,
    appSessionsThisWeek: 8,
    messagesWithDoctors: 4,
    lastActiveLabel: '1 hour ago',
    registrationWindowLabel: 'Ready for batch send',
    registrationAccessSent: false,
    overallGrade: 'B+',
    permissions: [
      _permission(
        'Course registration',
        'Ready for upcoming graduation term selection',
        true,
      ),
      _permission(
        'Graduation audit',
        'Audit access visible to advisors only',
        true,
      ),
      _permission(
        'Financial clearance',
        'No active finance restrictions',
        true,
      ),
    ],
    activeCourses: [
      _course(
        'IS401',
        'ERP Systems',
        'Dr. Rania Farid',
        3,
        0.77,
        89,
        84,
        'Healthy',
      ),
      _course(
        'IS402',
        'IT Governance',
        'Dr. Nader Mostafa',
        2,
        0.83,
        86,
        82,
        'Healthy',
      ),
    ],
    completedCourses: [
      _course(
        'IS322',
        'Project Management',
        'Dr. Dalia Hussein',
        3,
        1,
        91,
        88,
        'Completed',
      ),
    ],
    timeline: [
      _event(
        'Graduation audit updated',
        '24 credit hours remain before completion',
        'Today, 09:46',
        'graduation',
        'good',
      ),
      _event(
        'Registration campaign pending',
        'Awaiting batch-wide send action',
        'Yesterday',
        'registration',
        'attention',
      ),
    ],
    engagementTrend: const [
      StudentTrendPoint(label: 'Jan', value: 61),
      StudentTrendPoint(label: 'Feb', value: 65),
      StudentTrendPoint(label: 'Mar', value: 70),
      StudentTrendPoint(label: 'Apr', value: 74),
      StudentTrendPoint(label: 'May', value: 77),
      StudentTrendPoint(label: 'Jun', value: 80),
    ],
  ),
];

StudentAdminRecord _student({
  required String id,
  required String nationalId,
  required String fullName,
  required String email,
  required String phone,
  required String department,
  required String batch,
  required String academicLevel,
  required String section,
  required String status,
  required String advisorName,
  required double termGpa,
  required double cumulativeGpa,
  required double attendanceRate,
  required double subjectActivityRate,
  required double doctorInteractionRate,
  required int earnedCreditHours,
  required int remainingCreditHours,
  required int quizzesTaken,
  required int examsTaken,
  required int lecturesAttended,
  required int totalLectures,
  required int appSessionsThisWeek,
  required int messagesWithDoctors,
  required String lastActiveLabel,
  required String registrationWindowLabel,
  required bool registrationAccessSent,
  required String overallGrade,
  required List<StudentPermission> permissions,
  required List<StudentCourseProgress> activeCourses,
  required List<StudentCourseProgress> completedCourses,
  required List<StudentTimelineEvent> timeline,
  required List<StudentTrendPoint> engagementTrend,
}) {
  return StudentAdminRecord(
    id: id,
    nationalId: nationalId,
    fullName: fullName,
    email: email,
    phone: phone,
    department: department,
    batch: batch,
    academicLevel: academicLevel,
    section: section,
    status: status,
    advisorName: advisorName,
    termGpa: termGpa,
    cumulativeGpa: cumulativeGpa,
    attendanceRate: attendanceRate,
    subjectActivityRate: subjectActivityRate,
    doctorInteractionRate: doctorInteractionRate,
    earnedCreditHours: earnedCreditHours,
    remainingCreditHours: remainingCreditHours,
    totalCreditHours: 136,
    quizzesTaken: quizzesTaken,
    examsTaken: examsTaken,
    lecturesAttended: lecturesAttended,
    totalLectures: totalLectures,
    appSessionsThisWeek: appSessionsThisWeek,
    messagesWithDoctors: messagesWithDoctors,
    lastActiveLabel: lastActiveLabel,
    registrationWindowLabel: registrationWindowLabel,
    registrationAccessSent: registrationAccessSent,
    overallGrade: overallGrade,
    permissions: permissions,
    activeCourses: activeCourses,
    completedCourses: completedCourses,
    timeline: timeline,
    engagementTrend: engagementTrend,
  );
}

StudentPermission _permission(String title, String description, bool enabled) {
  return StudentPermission(
    title: title,
    description: description,
    enabled: enabled,
  );
}

StudentCourseProgress _course(
  String code,
  String title,
  String instructor,
  int credits,
  double progress,
  double attendanceRate,
  double currentMark,
  String status,
) {
  return StudentCourseProgress(
    code: code,
    title: title,
    instructor: instructor,
    credits: credits,
    progress: progress,
    attendanceRate: attendanceRate,
    currentMark: currentMark,
    status: status,
  );
}

StudentTimelineEvent _event(
  String title,
  String subtitle,
  String timeLabel,
  String kind,
  String emphasis,
) {
  return StudentTimelineEvent(
    title: title,
    subtitle: subtitle,
    timeLabel: timeLabel,
    kind: kind,
    emphasis: emphasis,
  );
}
