// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmS5XFMERMZ6RqFFZ8_oa5Qe3YcLSZ-S0',
    appId: '1:168050637950:web:3babe741ea3a35740aec2f',
    messagingSenderId: '168050637950',
    projectId: 'tolab-e1b84',
    authDomain: 'tolab-e1b84.firebaseapp.com',
    databaseURL: 'https://tolab-e1b84-default-rtdb.firebaseio.com',
    storageBucket: 'tolab-e1b84.firebasestorage.app',
    measurementId: 'G-7R397HKHWF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3Gt-paXdiUl7FR42asDauoHj5DmWr4gc',
    appId: '1:168050637950:android:27277792b18f19680aec2f',
    messagingSenderId: '168050637950',
    projectId: 'tolab-e1b84',
    databaseURL: 'https://tolab-e1b84-default-rtdb.firebaseio.com',
    storageBucket: 'tolab-e1b84.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAh26MjDkS9ovjsatkRR3RItAqwZQOjpNE',
    appId: '1:168050637950:ios:d306b318502e15310aec2f',
    messagingSenderId: '168050637950',
    projectId: 'tolab-e1b84',
    databaseURL: 'https://tolab-e1b84-default-rtdb.firebaseio.com',
    storageBucket: 'tolab-e1b84.firebasestorage.app',
    androidClientId: '168050637950-vt629lofge2cscbd4m3mtql3nic64fft.apps.googleusercontent.com',
    iosClientId: '168050637950-1jlle7e7qu8fjqqr5f8i98gm28ca34pr.apps.googleusercontent.com',
    iosBundleId: 'com.example.tolabFci',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAh26MjDkS9ovjsatkRR3RItAqwZQOjpNE',
    appId: '1:168050637950:ios:d306b318502e15310aec2f',
    messagingSenderId: '168050637950',
    projectId: 'tolab-e1b84',
    databaseURL: 'https://tolab-e1b84-default-rtdb.firebaseio.com',
    storageBucket: 'tolab-e1b84.firebasestorage.app',
    androidClientId: '168050637950-vt629lofge2cscbd4m3mtql3nic64fft.apps.googleusercontent.com',
    iosClientId: '168050637950-1jlle7e7qu8fjqqr5f8i98gm28ca34pr.apps.googleusercontent.com',
    iosBundleId: 'com.example.tolabFci',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmS5XFMERMZ6RqFFZ8_oa5Qe3YcLSZ-S0',
    appId: '1:168050637950:web:f24d806470f264e70aec2f',
    messagingSenderId: '168050637950',
    projectId: 'tolab-e1b84',
    authDomain: 'tolab-e1b84.firebaseapp.com',
    databaseURL: 'https://tolab-e1b84-default-rtdb.firebaseio.com',
    storageBucket: 'tolab-e1b84.firebasestorage.app',
    measurementId: 'G-7X3WCSM3EC',
  );
}
