"""Phase 1 Entities

Revision ID: a7b5f397cbd8
Revises: 16ca2efb6d0d
Create Date: 2026-02-20 23:15:16.982748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a7b5f397cbd8'
down_revision: Union[str, Sequence[str], None] = '16ca2efb6d0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auditlog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('resource', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('resource_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('details', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('refreshtoken',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jti', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refreshtoken_jti'), 'refreshtoken', ['jti'], unique=True)
    op.create_table('announcement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('body', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('pinned', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_announcement_subject_id'), 'announcement', ['subject_id'], unique=False)
    op.create_table('attendancesession',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('starts_at', sa.DateTime(), nullable=False),
    sa.Column('ends_at', sa.DateTime(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attendancesession_subject_id'), 'attendancesession', ['subject_id'], unique=False)
    op.create_table('quiz',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('start_at', sa.DateTime(), nullable=False),
    sa.Column('end_at', sa.DateTime(), nullable=False),
    sa.Column('duration_mins', sa.Integer(), nullable=False),
    sa.Column('total_points', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attendancerecord',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('checked_in_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['attendancesession.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attendancerecord_session_id'), 'attendancerecord', ['session_id'], unique=False)
    op.create_index(op.f('ix_attendancerecord_student_id'), 'attendancerecord', ['student_id'], unique=False)
    op.create_table('quizattempt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quiz_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['quiz_id'], ['quiz.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_enrollment_student_id'), 'enrollment', ['student_id'], unique=False)
    op.create_index(op.f('ix_enrollment_subject_id'), 'enrollment', ['subject_id'], unique=False)
    op.create_index(op.f('ix_notification_created_at'), 'notification', ['created_at'], unique=False)
    op.create_index(op.f('ix_post_author_id'), 'post', ['author_id'], unique=False)
    op.create_index(op.f('ix_post_subject_id'), 'post', ['subject_id'], unique=False)
    op.add_column('submission', sa.Column('feedback_comment', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('submission', sa.Column('graded_at', sa.DateTime(), nullable=True))
    op.add_column('submission', sa.Column('graded_by', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_submission_student_id'), 'submission', ['student_id'], unique=False)
    op.create_index(op.f('ix_submission_task_id'), 'submission', ['task_id'], unique=False)
    op.create_foreign_key(None, 'submission', 'user', ['graded_by'], ['id'])
    op.drop_column('submission', 'feedback')
    op.create_index(op.f('ix_task_subject_id'), 'task', ['subject_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_subject_id'), table_name='task')
    op.add_column('submission', sa.Column('feedback', sa.VARCHAR(), nullable=True))
    op.drop_constraint(None, 'submission', type_='foreignkey')
    op.drop_index(op.f('ix_submission_task_id'), table_name='submission')
    op.drop_index(op.f('ix_submission_student_id'), table_name='submission')
    op.drop_column('submission', 'graded_by')
    op.drop_column('submission', 'graded_at')
    op.drop_column('submission', 'feedback_comment')
    op.drop_index(op.f('ix_post_subject_id'), table_name='post')
    op.drop_index(op.f('ix_post_author_id'), table_name='post')
    op.drop_index(op.f('ix_notification_created_at'), table_name='notification')
    op.drop_index(op.f('ix_enrollment_subject_id'), table_name='enrollment')
    op.drop_index(op.f('ix_enrollment_student_id'), table_name='enrollment')
    op.drop_table('reaction')
    op.drop_table('quizattempt')
    op.drop_index(op.f('ix_attendancerecord_student_id'), table_name='attendancerecord')
    op.drop_index(op.f('ix_attendancerecord_session_id'), table_name='attendancerecord')
    op.drop_table('attendancerecord')
    op.drop_table('quiz')
    op.drop_index(op.f('ix_attendancesession_subject_id'), table_name='attendancesession')
    op.drop_table('attendancesession')
    op.drop_index(op.f('ix_announcement_subject_id'), table_name='announcement')
    op.drop_table('announcement')
    op.drop_index(op.f('ix_refreshtoken_jti'), table_name='refreshtoken')
    op.drop_table('refreshtoken')
    op.drop_table('auditlog')
    # ### end Alembic commands ###
