"""Add academic structure and student fields

Revision ID: e0d6014bb153
Revises: a7b5f397cbd8
Create Date: 2026-02-22 17:30:22.660199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e0d6014bb153'
down_revision: Union[str, Sequence[str], None] = 'a7b5f397cbd8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('academicyear',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('academicyear', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_academicyear_name'), ['name'], unique=False)

    op.create_table('department',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('department', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_department_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_department_name'), ['name'], unique=False)

    op.create_table('systemsettings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('default_language', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('allow_students_change_lang', sa.Boolean(), nullable=False),
    sa.Column('allow_staff_change_lang', sa.Boolean(), nullable=False),
    sa.Column('enable_notifications', sa.Boolean(), nullable=False),
    sa.Column('min_password_length', sa.Integer(), nullable=False),
    sa.Column('require_complex_password', sa.Boolean(), nullable=False),
    sa.Column('session_timeout_mins', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('student_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('national_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('dob', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('nationality', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('gender', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('department_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('academic_year_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('enrollment_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
        batch_op.add_column(sa.Column('year_of_admission', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('admission_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.create_index(batch_op.f('ix_user_student_code'), ['student_code'], unique=True)
        batch_op.create_unique_constraint('uq_user_national_id', ['national_id'])
        batch_op.create_foreign_key('fk_user_academic_year', 'academicyear', ['academic_year_id'], ['id'])
        batch_op.create_foreign_key('fk_user_department', 'department', ['department_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_index(batch_op.f('ix_user_student_code'))
        batch_op.drop_column('admission_type')
        batch_op.drop_column('year_of_admission')
        batch_op.drop_column('enrollment_status')
        batch_op.drop_column('academic_year_id')
        batch_op.drop_column('department_id')
        batch_op.drop_column('gender')
        batch_op.drop_column('nationality')
        batch_op.drop_column('dob')
        batch_op.drop_column('national_id')
        batch_op.drop_column('student_code')

    op.drop_table('systemsettings')
    with op.batch_alter_table('department', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_department_name'))
        batch_op.drop_index(batch_op.f('ix_department_code'))

    op.drop_table('department')
    with op.batch_alter_table('academicyear', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_academicyear_name'))

    op.drop_table('academicyear')
    # ### end Alembic commands ###
